using Microsoft.CodeAnalysis;

namespace SourceGenerators
{
    [Generator]
    public class HelloSourceGenerator : ISourceGenerator
    {
        public void Initialize(GeneratorInitializationContext context)
        {
        }

        public void Execute(GeneratorExecutionContext context)
        {
            // Find the main method
            var mainMethod = context.Compilation.GetEntryPoint(context.CancellationToken);

            if (mainMethod == null)
            {
                return;
            }

            // Build up the source code
            var source = $@"
                           // <auto-generated/>
                           using System;

                           namespace {mainMethod.ContainingNamespace.ToDisplayString()}
                           {{
                               public static partial class {mainMethod.ContainingType.Name}
                               {{
                                   static partial void HelloFrom(string name) =>
                                       Console.WriteLine($""Generator says: Hi from '{{name}}'"");
                               }}
                           }}
                           ";
            var typeName = mainMethod.ContainingType.Name;

            // Add the source code to the compilation
            context.AddSource($"{typeName}.g.cs", source);
        }
    }
}
